"""initial table

Revision ID: 675be7a96300
Revises: 
Create Date: 2023-03-13 00:57:32.019074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675be7a96300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('topic_task', sa.String(length=400), nullable=True),
    sa.Column('count_solution', sa.String(length=400), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('complexity', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
