data = ['*specialproblem',
         '2 - sat',
         'binarysearch',
         'bitmasks',
         'bruteforce',
         'chineseremaindertheorem',
         'combinatorics',
         'constructivealgorithms',
         'datastructures',
         'dfsandsimilar',
         'divideandconquer',
         'dp',
         'dsu',
         'expressionparsing',
         'fft',
         'flows',
         'games',
         'geometry',
         'graphmatchings',
         'graphs',
         'greedy',
         'hashing',
         'implementation',
         'interactive',
         'math',
         'matrices',
         'meet - in -the - middle',
         'numbertheory',
         'probabilities',
         'schedules',
         'shortestpaths',
         'sortings',
         'strings',
         'stringsuffixstructures',
         'ternarysearch',
         'trees',
         'twopointersexpressionparsing'
         ]


