from aiogram import types

buttons = ['*specialproblem',
           '2 - sat',
           'binarysearch',
           'bitmasks',
           'bruteforce',
           'chineseremaindertheorem',
           'combinatorics',
           'constructivealgorithms',
           'datastructures',
           'dfsandsimilar',
           'divideandconquer',
           'dp',
           'dsu',
           'expressionparsing',
           'fft',
           'flows',
           'games',
           'geometry',
           'graphmatchings',
           'graphs',
           'greedy',
           'hashing',
           'implementation',
           'interactive',
           'math',
           'matrices',
           'meet - in -the - middle',
           'numbertheory',
           'probabilities',
           'schedules',
           'shortestpaths',
           'sortings',
           'strings',
           'stringsuffixstructures',
           'ternarysearch',
           'trees',
           'twopointersexpressionparsing'
           ]

inline_buttons_theme = [types.InlineKeyboardButton(text=i, callback_data=f"data_{i}") for i in buttons]
